name: Daily Podcast Transcription

on:
  schedule:
    # Run at 7:00 AM on weekdays (Monday to Friday)
    - cron: '0 7 * * 1-5'
  workflow_dispatch:  # Allow manual triggering

jobs:
  transcribe:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run transcription script
      env:
        GLADIA_API_KEY: ${{ secrets.GLADIA_API_KEY }}
      run: python daily_transcription.py
        
    - name: Commit and push changes
      run: |
        git config --local user.email "github-actions@github.com"
        git config --local user.name "GitHub Actions"
        git add index.html archive/ transcriptions/
        git commit -m "Update transcription for $(date +'%Y-%m-%d')" || echo "No changes to commit"
        git push